version: '3'
services:
  transformer:
    build:
      context: .
    container_name: transformer
    environment:
      - ELASTIC_URL=${ELASTIC_URL}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_INDEX=${ELASTIC_INDEX}
      - FLASK_CONFIG=${FLASK_CONFIG}
      - NEURON_RTD_ADDRESS=unix:/sock/neuron.sock
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - '/tmp/neuron_rtd_sock/:/sock'
      - ./transformer_model/:/transformer_model/
    networks:
      - transformer_net
    depends_on: 
      # - node-1
      - neuron-rtd
    restart: always

  neuron-rtd:
    build:
      context: ./docker_dependencies
    container_name: neuron-rtd
    # environment:
    #   - AWS_NEURON_VISIBLE_DEVICES="0"
    devices:
      - "/dev/neuron0"
    cap_add:
      - IPC_LOCK
      - SYS_ADMIN
    volumes:
      - '/tmp/neuron_rtd_sock/:/sock'
    restart: always

networks:
  transformer_net:
    external: true