version: '3'
services:
  transformer:
    build:
      context: .
    container_name: transformer
    environment:
      - ELASTIC_URL=${ELASTIC_URL}
    ports:
      - 8000:8000
      - 5678:5678
    networks:
      - transformer_net
    depends_on: 
      - node-1
  node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: node-1
    environment:
      - ELASTIC_PASSWORD=changeme
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - cluster.name=dev_transformer_cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./docker_dependencies/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - docker_es_node_local_es_data:/usr/share/elasticsearch/data
    networks:
      - transformer_net
  kib:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kib
    environment: 
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - 5601:5601
    volumes:
      - ./docker_dependencies/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks: 
      - transformer_net
    depends_on: 
      - node-1
volumes:
  docker_es_node_local_es_data:
    external: true
networks:
  transformer_net:
    external: true