version: '3'
services:
  transformer:
    build:
      context: .
    container_name: transformer
    environment:
      - ELASTIC_URL=${ELASTIC_URL}
      - NEURON_RTD_ADDRESS=unix=/sock/neuron.sock
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - '/tmp/neuron_rtd_sock/:/sock'
    networks:
      - transformer_net
    depends_on: 
      - node-1
      - neuron-rtd
  node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: node-1
    environment:
      - ELASTIC_PASSWORD=changeme
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - cluster.name=dev_transformer_cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./docker_dependencies/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - docker_es_node_local_es_data:/usr/share/elasticsearch/data
    networks:
      - transformer_net
  neuron-rtd:
    build:
      context: ./docker_dependencies
    container_name: neuron-rtd
    devices:
      - "/dev/neuron0"
    environment:
      - AWS_NEURON_VISIBLE_DEVICES="0"
    cap_add:
      - IPC_LOCK
      - SYS_ADMIN
    volumes:
      - '/tmp/neuron_rtd_sock/:/sock'
volumes:
  docker_es_node_local_es_data:
    external: true
networks:
  transformer_net:
    external: true